version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: 4.x
  ignore:
  - dependency-name: org.jetbrains.dokka
    versions:
    - ">= 0.11.a"
    - "< 0.12"
  - dependency-name: org.objenesis:objenesis
    versions:
    - "> 2.6"
